### PR TITLE
use new raster package, use golang.org/x/image/math/fixed & regen shapefile

### PR DESCRIPTION
**Pull request by azr**
Howdy, this should fix #3 and #5

### CODE REVIEW

**Comment by azr** [comment]
I think I already signed that google sla thingy

**Comment by azr** [comment]
can you please confirm @ksimka ?

**Comment by ksimka** [comment]
I confirm. Is that enough? )

**Comment by azr** [comment]
bawmp !

**Comment by azr** [comment]
this is never going to come through 😬

**Comment by bradfitz** [comment]
Consider it bumped. I'll take a look.

**Comment by azr** [comment]
The path to merge is a bumpy road 😄

**Pull request merged**
